// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metting/metting.service.proto

package com.ljzn.grpc.metting;

/**
 * Protobuf type {@code MettingSystem.MettingEmpInfoResponse}
 */
public  final class MettingEmpInfoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MettingSystem.MettingEmpInfoResponse)
    MettingEmpInfoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MettingEmpInfoResponse.newBuilder() to construct.
  private MettingEmpInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MettingEmpInfoResponse() {
    code_ = 0;
    message_ = "";
    mettingEmpInfo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MettingEmpInfoResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            code_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              mettingEmpInfo_ = new java.util.ArrayList<com.ljzn.grpc.metting.MettingEmpInfo>();
              mutable_bitField0_ |= 0x00000004;
            }
            mettingEmpInfo_.add(
                input.readMessage(com.ljzn.grpc.metting.MettingEmpInfo.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        mettingEmpInfo_ = java.util.Collections.unmodifiableList(mettingEmpInfo_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ljzn.grpc.metting.MettingService.internal_static_MettingSystem_MettingEmpInfoResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ljzn.grpc.metting.MettingService.internal_static_MettingSystem_MettingEmpInfoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ljzn.grpc.metting.MettingEmpInfoResponse.class, com.ljzn.grpc.metting.MettingEmpInfoResponse.Builder.class);
  }

  private int bitField0_;
  public static final int CODE_FIELD_NUMBER = 1;
  private int code_;
  /**
   * <code>int32 code = 1;</code>
   */
  public int getCode() {
    return code_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 2;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METTINGEMPINFO_FIELD_NUMBER = 3;
  private java.util.List<com.ljzn.grpc.metting.MettingEmpInfo> mettingEmpInfo_;
  /**
   * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
   */
  public java.util.List<com.ljzn.grpc.metting.MettingEmpInfo> getMettingEmpInfoList() {
    return mettingEmpInfo_;
  }
  /**
   * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
   */
  public java.util.List<? extends com.ljzn.grpc.metting.MettingEmpInfoOrBuilder> 
      getMettingEmpInfoOrBuilderList() {
    return mettingEmpInfo_;
  }
  /**
   * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
   */
  public int getMettingEmpInfoCount() {
    return mettingEmpInfo_.size();
  }
  /**
   * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
   */
  public com.ljzn.grpc.metting.MettingEmpInfo getMettingEmpInfo(int index) {
    return mettingEmpInfo_.get(index);
  }
  /**
   * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
   */
  public com.ljzn.grpc.metting.MettingEmpInfoOrBuilder getMettingEmpInfoOrBuilder(
      int index) {
    return mettingEmpInfo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != 0) {
      output.writeInt32(1, code_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    for (int i = 0; i < mettingEmpInfo_.size(); i++) {
      output.writeMessage(3, mettingEmpInfo_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, code_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    for (int i = 0; i < mettingEmpInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, mettingEmpInfo_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ljzn.grpc.metting.MettingEmpInfoResponse)) {
      return super.equals(obj);
    }
    com.ljzn.grpc.metting.MettingEmpInfoResponse other = (com.ljzn.grpc.metting.MettingEmpInfoResponse) obj;

    boolean result = true;
    result = result && (getCode()
        == other.getCode());
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && getMettingEmpInfoList()
        .equals(other.getMettingEmpInfoList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (getMettingEmpInfoCount() > 0) {
      hash = (37 * hash) + METTINGEMPINFO_FIELD_NUMBER;
      hash = (53 * hash) + getMettingEmpInfoList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ljzn.grpc.metting.MettingEmpInfoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.metting.MettingEmpInfoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.metting.MettingEmpInfoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.metting.MettingEmpInfoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.metting.MettingEmpInfoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.metting.MettingEmpInfoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.metting.MettingEmpInfoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.metting.MettingEmpInfoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.metting.MettingEmpInfoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.metting.MettingEmpInfoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.metting.MettingEmpInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.metting.MettingEmpInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ljzn.grpc.metting.MettingEmpInfoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MettingSystem.MettingEmpInfoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MettingSystem.MettingEmpInfoResponse)
      com.ljzn.grpc.metting.MettingEmpInfoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljzn.grpc.metting.MettingService.internal_static_MettingSystem_MettingEmpInfoResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljzn.grpc.metting.MettingService.internal_static_MettingSystem_MettingEmpInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljzn.grpc.metting.MettingEmpInfoResponse.class, com.ljzn.grpc.metting.MettingEmpInfoResponse.Builder.class);
    }

    // Construct using com.ljzn.grpc.metting.MettingEmpInfoResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMettingEmpInfoFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      code_ = 0;

      message_ = "";

      if (mettingEmpInfoBuilder_ == null) {
        mettingEmpInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        mettingEmpInfoBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ljzn.grpc.metting.MettingService.internal_static_MettingSystem_MettingEmpInfoResponse_descriptor;
    }

    public com.ljzn.grpc.metting.MettingEmpInfoResponse getDefaultInstanceForType() {
      return com.ljzn.grpc.metting.MettingEmpInfoResponse.getDefaultInstance();
    }

    public com.ljzn.grpc.metting.MettingEmpInfoResponse build() {
      com.ljzn.grpc.metting.MettingEmpInfoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ljzn.grpc.metting.MettingEmpInfoResponse buildPartial() {
      com.ljzn.grpc.metting.MettingEmpInfoResponse result = new com.ljzn.grpc.metting.MettingEmpInfoResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.code_ = code_;
      result.message_ = message_;
      if (mettingEmpInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          mettingEmpInfo_ = java.util.Collections.unmodifiableList(mettingEmpInfo_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.mettingEmpInfo_ = mettingEmpInfo_;
      } else {
        result.mettingEmpInfo_ = mettingEmpInfoBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ljzn.grpc.metting.MettingEmpInfoResponse) {
        return mergeFrom((com.ljzn.grpc.metting.MettingEmpInfoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ljzn.grpc.metting.MettingEmpInfoResponse other) {
      if (other == com.ljzn.grpc.metting.MettingEmpInfoResponse.getDefaultInstance()) return this;
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (mettingEmpInfoBuilder_ == null) {
        if (!other.mettingEmpInfo_.isEmpty()) {
          if (mettingEmpInfo_.isEmpty()) {
            mettingEmpInfo_ = other.mettingEmpInfo_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureMettingEmpInfoIsMutable();
            mettingEmpInfo_.addAll(other.mettingEmpInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.mettingEmpInfo_.isEmpty()) {
          if (mettingEmpInfoBuilder_.isEmpty()) {
            mettingEmpInfoBuilder_.dispose();
            mettingEmpInfoBuilder_ = null;
            mettingEmpInfo_ = other.mettingEmpInfo_;
            bitField0_ = (bitField0_ & ~0x00000004);
            mettingEmpInfoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMettingEmpInfoFieldBuilder() : null;
          } else {
            mettingEmpInfoBuilder_.addAllMessages(other.mettingEmpInfo_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ljzn.grpc.metting.MettingEmpInfoResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ljzn.grpc.metting.MettingEmpInfoResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int code_ ;
    /**
     * <code>int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }
    /**
     * <code>int32 code = 1;</code>
     */
    public Builder setCode(int value) {
      
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 code = 1;</code>
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.ljzn.grpc.metting.MettingEmpInfo> mettingEmpInfo_ =
      java.util.Collections.emptyList();
    private void ensureMettingEmpInfoIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        mettingEmpInfo_ = new java.util.ArrayList<com.ljzn.grpc.metting.MettingEmpInfo>(mettingEmpInfo_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ljzn.grpc.metting.MettingEmpInfo, com.ljzn.grpc.metting.MettingEmpInfo.Builder, com.ljzn.grpc.metting.MettingEmpInfoOrBuilder> mettingEmpInfoBuilder_;

    /**
     * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
     */
    public java.util.List<com.ljzn.grpc.metting.MettingEmpInfo> getMettingEmpInfoList() {
      if (mettingEmpInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(mettingEmpInfo_);
      } else {
        return mettingEmpInfoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
     */
    public int getMettingEmpInfoCount() {
      if (mettingEmpInfoBuilder_ == null) {
        return mettingEmpInfo_.size();
      } else {
        return mettingEmpInfoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
     */
    public com.ljzn.grpc.metting.MettingEmpInfo getMettingEmpInfo(int index) {
      if (mettingEmpInfoBuilder_ == null) {
        return mettingEmpInfo_.get(index);
      } else {
        return mettingEmpInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
     */
    public Builder setMettingEmpInfo(
        int index, com.ljzn.grpc.metting.MettingEmpInfo value) {
      if (mettingEmpInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMettingEmpInfoIsMutable();
        mettingEmpInfo_.set(index, value);
        onChanged();
      } else {
        mettingEmpInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
     */
    public Builder setMettingEmpInfo(
        int index, com.ljzn.grpc.metting.MettingEmpInfo.Builder builderForValue) {
      if (mettingEmpInfoBuilder_ == null) {
        ensureMettingEmpInfoIsMutable();
        mettingEmpInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        mettingEmpInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
     */
    public Builder addMettingEmpInfo(com.ljzn.grpc.metting.MettingEmpInfo value) {
      if (mettingEmpInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMettingEmpInfoIsMutable();
        mettingEmpInfo_.add(value);
        onChanged();
      } else {
        mettingEmpInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
     */
    public Builder addMettingEmpInfo(
        int index, com.ljzn.grpc.metting.MettingEmpInfo value) {
      if (mettingEmpInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMettingEmpInfoIsMutable();
        mettingEmpInfo_.add(index, value);
        onChanged();
      } else {
        mettingEmpInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
     */
    public Builder addMettingEmpInfo(
        com.ljzn.grpc.metting.MettingEmpInfo.Builder builderForValue) {
      if (mettingEmpInfoBuilder_ == null) {
        ensureMettingEmpInfoIsMutable();
        mettingEmpInfo_.add(builderForValue.build());
        onChanged();
      } else {
        mettingEmpInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
     */
    public Builder addMettingEmpInfo(
        int index, com.ljzn.grpc.metting.MettingEmpInfo.Builder builderForValue) {
      if (mettingEmpInfoBuilder_ == null) {
        ensureMettingEmpInfoIsMutable();
        mettingEmpInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        mettingEmpInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
     */
    public Builder addAllMettingEmpInfo(
        java.lang.Iterable<? extends com.ljzn.grpc.metting.MettingEmpInfo> values) {
      if (mettingEmpInfoBuilder_ == null) {
        ensureMettingEmpInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mettingEmpInfo_);
        onChanged();
      } else {
        mettingEmpInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
     */
    public Builder clearMettingEmpInfo() {
      if (mettingEmpInfoBuilder_ == null) {
        mettingEmpInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        mettingEmpInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
     */
    public Builder removeMettingEmpInfo(int index) {
      if (mettingEmpInfoBuilder_ == null) {
        ensureMettingEmpInfoIsMutable();
        mettingEmpInfo_.remove(index);
        onChanged();
      } else {
        mettingEmpInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
     */
    public com.ljzn.grpc.metting.MettingEmpInfo.Builder getMettingEmpInfoBuilder(
        int index) {
      return getMettingEmpInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
     */
    public com.ljzn.grpc.metting.MettingEmpInfoOrBuilder getMettingEmpInfoOrBuilder(
        int index) {
      if (mettingEmpInfoBuilder_ == null) {
        return mettingEmpInfo_.get(index);  } else {
        return mettingEmpInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
     */
    public java.util.List<? extends com.ljzn.grpc.metting.MettingEmpInfoOrBuilder> 
         getMettingEmpInfoOrBuilderList() {
      if (mettingEmpInfoBuilder_ != null) {
        return mettingEmpInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(mettingEmpInfo_);
      }
    }
    /**
     * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
     */
    public com.ljzn.grpc.metting.MettingEmpInfo.Builder addMettingEmpInfoBuilder() {
      return getMettingEmpInfoFieldBuilder().addBuilder(
          com.ljzn.grpc.metting.MettingEmpInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
     */
    public com.ljzn.grpc.metting.MettingEmpInfo.Builder addMettingEmpInfoBuilder(
        int index) {
      return getMettingEmpInfoFieldBuilder().addBuilder(
          index, com.ljzn.grpc.metting.MettingEmpInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .MettingSystem.MettingEmpInfo mettingEmpInfo = 3;</code>
     */
    public java.util.List<com.ljzn.grpc.metting.MettingEmpInfo.Builder> 
         getMettingEmpInfoBuilderList() {
      return getMettingEmpInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ljzn.grpc.metting.MettingEmpInfo, com.ljzn.grpc.metting.MettingEmpInfo.Builder, com.ljzn.grpc.metting.MettingEmpInfoOrBuilder> 
        getMettingEmpInfoFieldBuilder() {
      if (mettingEmpInfoBuilder_ == null) {
        mettingEmpInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ljzn.grpc.metting.MettingEmpInfo, com.ljzn.grpc.metting.MettingEmpInfo.Builder, com.ljzn.grpc.metting.MettingEmpInfoOrBuilder>(
                mettingEmpInfo_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        mettingEmpInfo_ = null;
      }
      return mettingEmpInfoBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MettingSystem.MettingEmpInfoResponse)
  }

  // @@protoc_insertion_point(class_scope:MettingSystem.MettingEmpInfoResponse)
  private static final com.ljzn.grpc.metting.MettingEmpInfoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ljzn.grpc.metting.MettingEmpInfoResponse();
  }

  public static com.ljzn.grpc.metting.MettingEmpInfoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MettingEmpInfoResponse>
      PARSER = new com.google.protobuf.AbstractParser<MettingEmpInfoResponse>() {
    public MettingEmpInfoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MettingEmpInfoResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MettingEmpInfoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MettingEmpInfoResponse> getParserForType() {
    return PARSER;
  }

  public com.ljzn.grpc.metting.MettingEmpInfoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

