// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: department/department.service.proto

package com.ljzn.grpc.department;

public final class DepartmentService {
  private DepartmentService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VisitorSystem_cq_DepartmentDataApplyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VisitorSystem_cq_DepartmentDataApplyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VisitorSystem_cq_DepartmentDataApplyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VisitorSystem_cq_DepartmentDataApplyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#department/department.service.proto\022\020V" +
      "isitorSystem_cq\032#department/department.m" +
      "essage.proto\"i\n\032DepartmentDataApplyReque" +
      "st\022\021\n\tclient_id\030\001 \001(\t\022\025\n\rclient_secret\030\002" +
      " \001(\t\022\017\n\007version\030\003 \001(\003\022\020\n\010belongId\030\004 \001(\005\"" +
      "\253\001\n\033DepartmentDataApplyResponse\022\014\n\004code\030" +
      "\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\025\n\rserver_secret\030" +
      "\003 \001(\t\022\025\n\rserverVersion\030\004 \001(\003\022?\n\022departme" +
      "ntMessages\030\005 \003(\0132#.VisitorSystem_cq.Depa" +
      "rtmentMessage2\215\001\n\025DepartmentAuthService\022" +
      "t\n\023DepartmentDataApply\022,.VisitorSystem_c" +
      "q.DepartmentDataApplyRequest\032-.VisitorSy" +
      "stem_cq.DepartmentDataApplyResponse\"\000B)\n" +
      "\030com.ljzn.grpc.departmentP\001\242\002\nDEPARTMENT" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ljzn.grpc.department.DepartmentMessageOuterClass.getDescriptor(),
        }, assigner);
    internal_static_VisitorSystem_cq_DepartmentDataApplyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VisitorSystem_cq_DepartmentDataApplyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VisitorSystem_cq_DepartmentDataApplyRequest_descriptor,
        new java.lang.String[] { "ClientId", "ClientSecret", "Version", "BelongId", });
    internal_static_VisitorSystem_cq_DepartmentDataApplyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_VisitorSystem_cq_DepartmentDataApplyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VisitorSystem_cq_DepartmentDataApplyResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "ServerSecret", "ServerVersion", "DepartmentMessages", });
    com.ljzn.grpc.department.DepartmentMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
