// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: department/department.message.proto

package com.ljzn.grpc.department;

/**
 * Protobuf type {@code VisitorSystem_cq.DepartmentMessage}
 */
public  final class DepartmentMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:VisitorSystem_cq.DepartmentMessage)
    DepartmentMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DepartmentMessage.newBuilder() to construct.
  private DepartmentMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DepartmentMessage() {
    departmentId_ = 0;
    departmentName_ = "";
    belongId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DepartmentMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            departmentId_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            departmentName_ = s;
            break;
          }
          case 24: {

            belongId_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ljzn.grpc.department.DepartmentMessageOuterClass.internal_static_VisitorSystem_cq_DepartmentMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ljzn.grpc.department.DepartmentMessageOuterClass.internal_static_VisitorSystem_cq_DepartmentMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ljzn.grpc.department.DepartmentMessage.class, com.ljzn.grpc.department.DepartmentMessage.Builder.class);
  }

  public static final int DEPARTMENTID_FIELD_NUMBER = 1;
  private int departmentId_;
  /**
   * <pre>
   *uuid
   * </pre>
   *
   * <code>int32 departmentId = 1;</code>
   */
  public int getDepartmentId() {
    return departmentId_;
  }

  public static final int DEPARTMENTNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object departmentName_;
  /**
   * <code>string departmentName = 2;</code>
   */
  public java.lang.String getDepartmentName() {
    java.lang.Object ref = departmentName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      departmentName_ = s;
      return s;
    }
  }
  /**
   * <code>string departmentName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDepartmentNameBytes() {
    java.lang.Object ref = departmentName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      departmentName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BELONGID_FIELD_NUMBER = 3;
  private int belongId_;
  /**
   * <code>int32 belongId = 3;</code>
   */
  public int getBelongId() {
    return belongId_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (departmentId_ != 0) {
      output.writeInt32(1, departmentId_);
    }
    if (!getDepartmentNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, departmentName_);
    }
    if (belongId_ != 0) {
      output.writeInt32(3, belongId_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (departmentId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, departmentId_);
    }
    if (!getDepartmentNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, departmentName_);
    }
    if (belongId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, belongId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ljzn.grpc.department.DepartmentMessage)) {
      return super.equals(obj);
    }
    com.ljzn.grpc.department.DepartmentMessage other = (com.ljzn.grpc.department.DepartmentMessage) obj;

    boolean result = true;
    result = result && (getDepartmentId()
        == other.getDepartmentId());
    result = result && getDepartmentName()
        .equals(other.getDepartmentName());
    result = result && (getBelongId()
        == other.getBelongId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DEPARTMENTID_FIELD_NUMBER;
    hash = (53 * hash) + getDepartmentId();
    hash = (37 * hash) + DEPARTMENTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getDepartmentName().hashCode();
    hash = (37 * hash) + BELONGID_FIELD_NUMBER;
    hash = (53 * hash) + getBelongId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ljzn.grpc.department.DepartmentMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.department.DepartmentMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.department.DepartmentMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.department.DepartmentMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.department.DepartmentMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.department.DepartmentMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.department.DepartmentMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.department.DepartmentMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.department.DepartmentMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.department.DepartmentMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.department.DepartmentMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.department.DepartmentMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ljzn.grpc.department.DepartmentMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code VisitorSystem_cq.DepartmentMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:VisitorSystem_cq.DepartmentMessage)
      com.ljzn.grpc.department.DepartmentMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljzn.grpc.department.DepartmentMessageOuterClass.internal_static_VisitorSystem_cq_DepartmentMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljzn.grpc.department.DepartmentMessageOuterClass.internal_static_VisitorSystem_cq_DepartmentMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljzn.grpc.department.DepartmentMessage.class, com.ljzn.grpc.department.DepartmentMessage.Builder.class);
    }

    // Construct using com.ljzn.grpc.department.DepartmentMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      departmentId_ = 0;

      departmentName_ = "";

      belongId_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ljzn.grpc.department.DepartmentMessageOuterClass.internal_static_VisitorSystem_cq_DepartmentMessage_descriptor;
    }

    public com.ljzn.grpc.department.DepartmentMessage getDefaultInstanceForType() {
      return com.ljzn.grpc.department.DepartmentMessage.getDefaultInstance();
    }

    public com.ljzn.grpc.department.DepartmentMessage build() {
      com.ljzn.grpc.department.DepartmentMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ljzn.grpc.department.DepartmentMessage buildPartial() {
      com.ljzn.grpc.department.DepartmentMessage result = new com.ljzn.grpc.department.DepartmentMessage(this);
      result.departmentId_ = departmentId_;
      result.departmentName_ = departmentName_;
      result.belongId_ = belongId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ljzn.grpc.department.DepartmentMessage) {
        return mergeFrom((com.ljzn.grpc.department.DepartmentMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ljzn.grpc.department.DepartmentMessage other) {
      if (other == com.ljzn.grpc.department.DepartmentMessage.getDefaultInstance()) return this;
      if (other.getDepartmentId() != 0) {
        setDepartmentId(other.getDepartmentId());
      }
      if (!other.getDepartmentName().isEmpty()) {
        departmentName_ = other.departmentName_;
        onChanged();
      }
      if (other.getBelongId() != 0) {
        setBelongId(other.getBelongId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ljzn.grpc.department.DepartmentMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ljzn.grpc.department.DepartmentMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int departmentId_ ;
    /**
     * <pre>
     *uuid
     * </pre>
     *
     * <code>int32 departmentId = 1;</code>
     */
    public int getDepartmentId() {
      return departmentId_;
    }
    /**
     * <pre>
     *uuid
     * </pre>
     *
     * <code>int32 departmentId = 1;</code>
     */
    public Builder setDepartmentId(int value) {
      
      departmentId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *uuid
     * </pre>
     *
     * <code>int32 departmentId = 1;</code>
     */
    public Builder clearDepartmentId() {
      
      departmentId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object departmentName_ = "";
    /**
     * <code>string departmentName = 2;</code>
     */
    public java.lang.String getDepartmentName() {
      java.lang.Object ref = departmentName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        departmentName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string departmentName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDepartmentNameBytes() {
      java.lang.Object ref = departmentName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        departmentName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string departmentName = 2;</code>
     */
    public Builder setDepartmentName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      departmentName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string departmentName = 2;</code>
     */
    public Builder clearDepartmentName() {
      
      departmentName_ = getDefaultInstance().getDepartmentName();
      onChanged();
      return this;
    }
    /**
     * <code>string departmentName = 2;</code>
     */
    public Builder setDepartmentNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      departmentName_ = value;
      onChanged();
      return this;
    }

    private int belongId_ ;
    /**
     * <code>int32 belongId = 3;</code>
     */
    public int getBelongId() {
      return belongId_;
    }
    /**
     * <code>int32 belongId = 3;</code>
     */
    public Builder setBelongId(int value) {
      
      belongId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 belongId = 3;</code>
     */
    public Builder clearBelongId() {
      
      belongId_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:VisitorSystem_cq.DepartmentMessage)
  }

  // @@protoc_insertion_point(class_scope:VisitorSystem_cq.DepartmentMessage)
  private static final com.ljzn.grpc.department.DepartmentMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ljzn.grpc.department.DepartmentMessage();
  }

  public static com.ljzn.grpc.department.DepartmentMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DepartmentMessage>
      PARSER = new com.google.protobuf.AbstractParser<DepartmentMessage>() {
    public DepartmentMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DepartmentMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DepartmentMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DepartmentMessage> getParserForType() {
    return PARSER;
  }

  public com.ljzn.grpc.department.DepartmentMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

