// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blacklist/blacklist.message.proto

package com.ljzn.grpc.blacklist;

public final class BlacklistMessageOuterClass {
  private BlacklistMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VisitorSystem_cq_BlacklistMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VisitorSystem_cq_BlacklistMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!blacklist/blacklist.message.proto\022\020Vis" +
      "itorSystem_cq\"Y\n\020BlacklistMessage\022\n\n\002id\030" +
      "\001 \001(\005\022\021\n\tvisitorId\030\002 \001(\t\022\024\n\014photoFeature" +
      "\030\003 \001(\014\022\020\n\010belongId\030\004 \001(\005B\'\n\027com.ljzn.grp" +
      "c.blacklistP\001\242\002\tBLACKLISTb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_VisitorSystem_cq_BlacklistMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VisitorSystem_cq_BlacklistMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VisitorSystem_cq_BlacklistMessage_descriptor,
        new java.lang.String[] { "Id", "VisitorId", "PhotoFeature", "BelongId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
