// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client/client.message.proto

package com.ljzn.grpc.client;

public interface ClientMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VisitorSystem_cq.ClientMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *uuid
   * </pre>
   *
   * <code>string deviceId = 1;</code>
   */
  java.lang.String getDeviceId();
  /**
   * <pre>
   *uuid
   * </pre>
   *
   * <code>string deviceId = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>string ip = 2;</code>
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 2;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int32 port = 3;</code>
   */
  int getPort();

  /**
   * <code>string parameter = 4;</code>
   */
  java.lang.String getParameter();
  /**
   * <code>string parameter = 4;</code>
   */
  com.google.protobuf.ByteString
      getParameterBytes();

  /**
   * <code>int32 type = 5;</code>
   */
  int getType();

  /**
   * <code>string address = 6;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 6;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string description = 7;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 7;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>int32 belongId = 8;</code>
   */
  int getBelongId();
}
