// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client/client.service.proto

package com.ljzn.grpc.client;

public interface HeartbeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VisitorSystem_cq.HeartbeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int64 counter = 3;</code>
   */
  long getCounter();
}
