// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attence/attence.message.proto

package com.ljzn.grpc.attence;

public interface AttenceMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AttenceSystem.AttenceMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string employeeId = 1;</code>
   */
  java.lang.String getEmployeeId();
  /**
   * <code>string employeeId = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmployeeIdBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *yy-MM-dd HH:mm:ss
   * </pre>
   *
   * <code>string workDate = 3;</code>
   */
  java.lang.String getWorkDate();
  /**
   * <pre>
   *yy-MM-dd HH:mm:ss
   * </pre>
   *
   * <code>string workDate = 3;</code>
   */
  com.google.protobuf.ByteString
      getWorkDateBytes();

  /**
   * <code>bytes camreaPhoto = 4;</code>
   */
  com.google.protobuf.ByteString getCamreaPhoto();
}
