// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attence/attence.message.proto

package com.ljzn.grpc.attence;

public final class AttenceMessageOuterClass {
  private AttenceMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AttenceSystem_AttenceMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AttenceSystem_AttenceMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AttenceSystem_EmployeeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AttenceSystem_EmployeeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AttenceSystem_EmployeeVersion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AttenceSystem_EmployeeVersion_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035attence/attence.message.proto\022\rAttence" +
      "System\"Y\n\016AttenceMessage\022\022\n\nemployeeId\030\001" +
      " \001(\t\022\014\n\004name\030\002 \001(\t\022\020\n\010workDate\030\003 \001(\t\022\023\n\013" +
      "camreaPhoto\030\004 \001(\014\"g\n\014EmployeeInfo\022\022\n\nemp" +
      "loyeeId\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\024\n\014photoFeat" +
      "ure\030\003 \001(\014\022\017\n\007version\030\004 \001(\003\022\016\n\006ICcard\030\005 \001" +
      "(\t\"\"\n\017EmployeeVersion\022\017\n\007version\030\001 \001(\003B#" +
      "\n\025com.ljzn.grpc.attenceP\001\242\002\007ATTENCEb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AttenceSystem_AttenceMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AttenceSystem_AttenceMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AttenceSystem_AttenceMessage_descriptor,
        new java.lang.String[] { "EmployeeId", "Name", "WorkDate", "CamreaPhoto", });
    internal_static_AttenceSystem_EmployeeInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AttenceSystem_EmployeeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AttenceSystem_EmployeeInfo_descriptor,
        new java.lang.String[] { "EmployeeId", "Name", "PhotoFeature", "Version", "ICcard", });
    internal_static_AttenceSystem_EmployeeVersion_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AttenceSystem_EmployeeVersion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AttenceSystem_EmployeeVersion_descriptor,
        new java.lang.String[] { "Version", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
