// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attence/attence.service.proto

package com.ljzn.grpc.attence;

public interface EmployeeVersionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AttenceSystem.EmployeeVersionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string versionName = 1;</code>
   */
  java.lang.String getVersionName();
  /**
   * <code>string versionName = 1;</code>
   */
  com.google.protobuf.ByteString
      getVersionNameBytes();
}
