// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attence/attence.service.proto

package com.ljzn.grpc.attence;

public interface EmployeeVersionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AttenceSystem.EmployeeVersionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 version = 1;</code>
   */
  long getVersion();
}
