// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attence/attence.service.proto

package com.ljzn.grpc.attence;

/**
 * Protobuf type {@code AttenceSystem.EmployeeInfoResponse}
 */
public  final class EmployeeInfoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AttenceSystem.EmployeeInfoResponse)
    EmployeeInfoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EmployeeInfoResponse.newBuilder() to construct.
  private EmployeeInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EmployeeInfoResponse() {
    code_ = 0;
    message_ = "";
    employeeInfo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EmployeeInfoResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            code_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              employeeInfo_ = new java.util.ArrayList<com.ljzn.grpc.attence.EmployeeInfo>();
              mutable_bitField0_ |= 0x00000004;
            }
            employeeInfo_.add(
                input.readMessage(com.ljzn.grpc.attence.EmployeeInfo.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        employeeInfo_ = java.util.Collections.unmodifiableList(employeeInfo_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ljzn.grpc.attence.AttenceService.internal_static_AttenceSystem_EmployeeInfoResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ljzn.grpc.attence.AttenceService.internal_static_AttenceSystem_EmployeeInfoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ljzn.grpc.attence.EmployeeInfoResponse.class, com.ljzn.grpc.attence.EmployeeInfoResponse.Builder.class);
  }

  private int bitField0_;
  public static final int CODE_FIELD_NUMBER = 1;
  private int code_;
  /**
   * <pre>
   *返回0失败
   * </pre>
   *
   * <code>int32 code = 1;</code>
   */
  public int getCode() {
    return code_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 2;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMPLOYEEINFO_FIELD_NUMBER = 4;
  private java.util.List<com.ljzn.grpc.attence.EmployeeInfo> employeeInfo_;
  /**
   * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
   */
  public java.util.List<com.ljzn.grpc.attence.EmployeeInfo> getEmployeeInfoList() {
    return employeeInfo_;
  }
  /**
   * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
   */
  public java.util.List<? extends com.ljzn.grpc.attence.EmployeeInfoOrBuilder> 
      getEmployeeInfoOrBuilderList() {
    return employeeInfo_;
  }
  /**
   * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
   */
  public int getEmployeeInfoCount() {
    return employeeInfo_.size();
  }
  /**
   * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
   */
  public com.ljzn.grpc.attence.EmployeeInfo getEmployeeInfo(int index) {
    return employeeInfo_.get(index);
  }
  /**
   * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
   */
  public com.ljzn.grpc.attence.EmployeeInfoOrBuilder getEmployeeInfoOrBuilder(
      int index) {
    return employeeInfo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != 0) {
      output.writeInt32(1, code_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    for (int i = 0; i < employeeInfo_.size(); i++) {
      output.writeMessage(4, employeeInfo_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, code_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    for (int i = 0; i < employeeInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, employeeInfo_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ljzn.grpc.attence.EmployeeInfoResponse)) {
      return super.equals(obj);
    }
    com.ljzn.grpc.attence.EmployeeInfoResponse other = (com.ljzn.grpc.attence.EmployeeInfoResponse) obj;

    boolean result = true;
    result = result && (getCode()
        == other.getCode());
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && getEmployeeInfoList()
        .equals(other.getEmployeeInfoList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (getEmployeeInfoCount() > 0) {
      hash = (37 * hash) + EMPLOYEEINFO_FIELD_NUMBER;
      hash = (53 * hash) + getEmployeeInfoList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ljzn.grpc.attence.EmployeeInfoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.attence.EmployeeInfoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.attence.EmployeeInfoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.attence.EmployeeInfoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.attence.EmployeeInfoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.attence.EmployeeInfoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.attence.EmployeeInfoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.attence.EmployeeInfoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.attence.EmployeeInfoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.attence.EmployeeInfoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.attence.EmployeeInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.attence.EmployeeInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ljzn.grpc.attence.EmployeeInfoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AttenceSystem.EmployeeInfoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AttenceSystem.EmployeeInfoResponse)
      com.ljzn.grpc.attence.EmployeeInfoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljzn.grpc.attence.AttenceService.internal_static_AttenceSystem_EmployeeInfoResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljzn.grpc.attence.AttenceService.internal_static_AttenceSystem_EmployeeInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljzn.grpc.attence.EmployeeInfoResponse.class, com.ljzn.grpc.attence.EmployeeInfoResponse.Builder.class);
    }

    // Construct using com.ljzn.grpc.attence.EmployeeInfoResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEmployeeInfoFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      code_ = 0;

      message_ = "";

      if (employeeInfoBuilder_ == null) {
        employeeInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        employeeInfoBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ljzn.grpc.attence.AttenceService.internal_static_AttenceSystem_EmployeeInfoResponse_descriptor;
    }

    public com.ljzn.grpc.attence.EmployeeInfoResponse getDefaultInstanceForType() {
      return com.ljzn.grpc.attence.EmployeeInfoResponse.getDefaultInstance();
    }

    public com.ljzn.grpc.attence.EmployeeInfoResponse build() {
      com.ljzn.grpc.attence.EmployeeInfoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ljzn.grpc.attence.EmployeeInfoResponse buildPartial() {
      com.ljzn.grpc.attence.EmployeeInfoResponse result = new com.ljzn.grpc.attence.EmployeeInfoResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.code_ = code_;
      result.message_ = message_;
      if (employeeInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          employeeInfo_ = java.util.Collections.unmodifiableList(employeeInfo_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.employeeInfo_ = employeeInfo_;
      } else {
        result.employeeInfo_ = employeeInfoBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ljzn.grpc.attence.EmployeeInfoResponse) {
        return mergeFrom((com.ljzn.grpc.attence.EmployeeInfoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ljzn.grpc.attence.EmployeeInfoResponse other) {
      if (other == com.ljzn.grpc.attence.EmployeeInfoResponse.getDefaultInstance()) return this;
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (employeeInfoBuilder_ == null) {
        if (!other.employeeInfo_.isEmpty()) {
          if (employeeInfo_.isEmpty()) {
            employeeInfo_ = other.employeeInfo_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureEmployeeInfoIsMutable();
            employeeInfo_.addAll(other.employeeInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.employeeInfo_.isEmpty()) {
          if (employeeInfoBuilder_.isEmpty()) {
            employeeInfoBuilder_.dispose();
            employeeInfoBuilder_ = null;
            employeeInfo_ = other.employeeInfo_;
            bitField0_ = (bitField0_ & ~0x00000004);
            employeeInfoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEmployeeInfoFieldBuilder() : null;
          } else {
            employeeInfoBuilder_.addAllMessages(other.employeeInfo_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ljzn.grpc.attence.EmployeeInfoResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ljzn.grpc.attence.EmployeeInfoResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int code_ ;
    /**
     * <pre>
     *返回0失败
     * </pre>
     *
     * <code>int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }
    /**
     * <pre>
     *返回0失败
     * </pre>
     *
     * <code>int32 code = 1;</code>
     */
    public Builder setCode(int value) {
      
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *返回0失败
     * </pre>
     *
     * <code>int32 code = 1;</code>
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.ljzn.grpc.attence.EmployeeInfo> employeeInfo_ =
      java.util.Collections.emptyList();
    private void ensureEmployeeInfoIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        employeeInfo_ = new java.util.ArrayList<com.ljzn.grpc.attence.EmployeeInfo>(employeeInfo_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ljzn.grpc.attence.EmployeeInfo, com.ljzn.grpc.attence.EmployeeInfo.Builder, com.ljzn.grpc.attence.EmployeeInfoOrBuilder> employeeInfoBuilder_;

    /**
     * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
     */
    public java.util.List<com.ljzn.grpc.attence.EmployeeInfo> getEmployeeInfoList() {
      if (employeeInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(employeeInfo_);
      } else {
        return employeeInfoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
     */
    public int getEmployeeInfoCount() {
      if (employeeInfoBuilder_ == null) {
        return employeeInfo_.size();
      } else {
        return employeeInfoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
     */
    public com.ljzn.grpc.attence.EmployeeInfo getEmployeeInfo(int index) {
      if (employeeInfoBuilder_ == null) {
        return employeeInfo_.get(index);
      } else {
        return employeeInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
     */
    public Builder setEmployeeInfo(
        int index, com.ljzn.grpc.attence.EmployeeInfo value) {
      if (employeeInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeeInfoIsMutable();
        employeeInfo_.set(index, value);
        onChanged();
      } else {
        employeeInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
     */
    public Builder setEmployeeInfo(
        int index, com.ljzn.grpc.attence.EmployeeInfo.Builder builderForValue) {
      if (employeeInfoBuilder_ == null) {
        ensureEmployeeInfoIsMutable();
        employeeInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        employeeInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
     */
    public Builder addEmployeeInfo(com.ljzn.grpc.attence.EmployeeInfo value) {
      if (employeeInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeeInfoIsMutable();
        employeeInfo_.add(value);
        onChanged();
      } else {
        employeeInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
     */
    public Builder addEmployeeInfo(
        int index, com.ljzn.grpc.attence.EmployeeInfo value) {
      if (employeeInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeeInfoIsMutable();
        employeeInfo_.add(index, value);
        onChanged();
      } else {
        employeeInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
     */
    public Builder addEmployeeInfo(
        com.ljzn.grpc.attence.EmployeeInfo.Builder builderForValue) {
      if (employeeInfoBuilder_ == null) {
        ensureEmployeeInfoIsMutable();
        employeeInfo_.add(builderForValue.build());
        onChanged();
      } else {
        employeeInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
     */
    public Builder addEmployeeInfo(
        int index, com.ljzn.grpc.attence.EmployeeInfo.Builder builderForValue) {
      if (employeeInfoBuilder_ == null) {
        ensureEmployeeInfoIsMutable();
        employeeInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        employeeInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
     */
    public Builder addAllEmployeeInfo(
        java.lang.Iterable<? extends com.ljzn.grpc.attence.EmployeeInfo> values) {
      if (employeeInfoBuilder_ == null) {
        ensureEmployeeInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, employeeInfo_);
        onChanged();
      } else {
        employeeInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
     */
    public Builder clearEmployeeInfo() {
      if (employeeInfoBuilder_ == null) {
        employeeInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        employeeInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
     */
    public Builder removeEmployeeInfo(int index) {
      if (employeeInfoBuilder_ == null) {
        ensureEmployeeInfoIsMutable();
        employeeInfo_.remove(index);
        onChanged();
      } else {
        employeeInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
     */
    public com.ljzn.grpc.attence.EmployeeInfo.Builder getEmployeeInfoBuilder(
        int index) {
      return getEmployeeInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
     */
    public com.ljzn.grpc.attence.EmployeeInfoOrBuilder getEmployeeInfoOrBuilder(
        int index) {
      if (employeeInfoBuilder_ == null) {
        return employeeInfo_.get(index);  } else {
        return employeeInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
     */
    public java.util.List<? extends com.ljzn.grpc.attence.EmployeeInfoOrBuilder> 
         getEmployeeInfoOrBuilderList() {
      if (employeeInfoBuilder_ != null) {
        return employeeInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(employeeInfo_);
      }
    }
    /**
     * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
     */
    public com.ljzn.grpc.attence.EmployeeInfo.Builder addEmployeeInfoBuilder() {
      return getEmployeeInfoFieldBuilder().addBuilder(
          com.ljzn.grpc.attence.EmployeeInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
     */
    public com.ljzn.grpc.attence.EmployeeInfo.Builder addEmployeeInfoBuilder(
        int index) {
      return getEmployeeInfoFieldBuilder().addBuilder(
          index, com.ljzn.grpc.attence.EmployeeInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .AttenceSystem.EmployeeInfo employeeInfo = 4;</code>
     */
    public java.util.List<com.ljzn.grpc.attence.EmployeeInfo.Builder> 
         getEmployeeInfoBuilderList() {
      return getEmployeeInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ljzn.grpc.attence.EmployeeInfo, com.ljzn.grpc.attence.EmployeeInfo.Builder, com.ljzn.grpc.attence.EmployeeInfoOrBuilder> 
        getEmployeeInfoFieldBuilder() {
      if (employeeInfoBuilder_ == null) {
        employeeInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ljzn.grpc.attence.EmployeeInfo, com.ljzn.grpc.attence.EmployeeInfo.Builder, com.ljzn.grpc.attence.EmployeeInfoOrBuilder>(
                employeeInfo_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        employeeInfo_ = null;
      }
      return employeeInfoBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AttenceSystem.EmployeeInfoResponse)
  }

  // @@protoc_insertion_point(class_scope:AttenceSystem.EmployeeInfoResponse)
  private static final com.ljzn.grpc.attence.EmployeeInfoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ljzn.grpc.attence.EmployeeInfoResponse();
  }

  public static com.ljzn.grpc.attence.EmployeeInfoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmployeeInfoResponse>
      PARSER = new com.google.protobuf.AbstractParser<EmployeeInfoResponse>() {
    public EmployeeInfoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EmployeeInfoResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EmployeeInfoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmployeeInfoResponse> getParserForType() {
    return PARSER;
  }

  public com.ljzn.grpc.attence.EmployeeInfoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

