// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attence/attence.service.proto

package com.ljzn.grpc.attence;

public interface getPhotoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AttenceSystem.getPhotoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes photo = 1;</code>
   */
  com.google.protobuf.ByteString getPhoto();
}
