// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee/employee.service.proto

package com.ljzn.grpc.employee;

/**
 * Protobuf type {@code VisitorSystem_cq.EmployeeDataApplyResponse}
 */
public  final class EmployeeDataApplyResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:VisitorSystem_cq.EmployeeDataApplyResponse)
    EmployeeDataApplyResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EmployeeDataApplyResponse.newBuilder() to construct.
  private EmployeeDataApplyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EmployeeDataApplyResponse() {
    code_ = 0;
    message_ = "";
    serverSecret_ = "";
    serverVersion_ = 0L;
    employeeMessages_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EmployeeDataApplyResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            code_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            serverSecret_ = s;
            break;
          }
          case 32: {

            serverVersion_ = input.readInt64();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              employeeMessages_ = new java.util.ArrayList<com.ljzn.grpc.employee.EmployeeMessage>();
              mutable_bitField0_ |= 0x00000010;
            }
            employeeMessages_.add(
                input.readMessage(com.ljzn.grpc.employee.EmployeeMessage.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        employeeMessages_ = java.util.Collections.unmodifiableList(employeeMessages_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ljzn.grpc.employee.EmployeeService.internal_static_VisitorSystem_cq_EmployeeDataApplyResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ljzn.grpc.employee.EmployeeService.internal_static_VisitorSystem_cq_EmployeeDataApplyResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ljzn.grpc.employee.EmployeeDataApplyResponse.class, com.ljzn.grpc.employee.EmployeeDataApplyResponse.Builder.class);
  }

  private int bitField0_;
  public static final int CODE_FIELD_NUMBER = 1;
  private int code_;
  /**
   * <code>int32 code = 1;</code>
   */
  public int getCode() {
    return code_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 2;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVER_SECRET_FIELD_NUMBER = 3;
  private volatile java.lang.Object serverSecret_;
  /**
   * <code>string server_secret = 3;</code>
   */
  public java.lang.String getServerSecret() {
    java.lang.Object ref = serverSecret_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serverSecret_ = s;
      return s;
    }
  }
  /**
   * <code>string server_secret = 3;</code>
   */
  public com.google.protobuf.ByteString
      getServerSecretBytes() {
    java.lang.Object ref = serverSecret_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serverSecret_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVERVERSION_FIELD_NUMBER = 4;
  private long serverVersion_;
  /**
   * <code>int64 serverVersion = 4;</code>
   */
  public long getServerVersion() {
    return serverVersion_;
  }

  public static final int EMPLOYEEMESSAGES_FIELD_NUMBER = 5;
  private java.util.List<com.ljzn.grpc.employee.EmployeeMessage> employeeMessages_;
  /**
   * <pre>
   *返回当前版本下的所有员工信息
   * </pre>
   *
   * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
   */
  public java.util.List<com.ljzn.grpc.employee.EmployeeMessage> getEmployeeMessagesList() {
    return employeeMessages_;
  }
  /**
   * <pre>
   *返回当前版本下的所有员工信息
   * </pre>
   *
   * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
   */
  public java.util.List<? extends com.ljzn.grpc.employee.EmployeeMessageOrBuilder> 
      getEmployeeMessagesOrBuilderList() {
    return employeeMessages_;
  }
  /**
   * <pre>
   *返回当前版本下的所有员工信息
   * </pre>
   *
   * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
   */
  public int getEmployeeMessagesCount() {
    return employeeMessages_.size();
  }
  /**
   * <pre>
   *返回当前版本下的所有员工信息
   * </pre>
   *
   * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
   */
  public com.ljzn.grpc.employee.EmployeeMessage getEmployeeMessages(int index) {
    return employeeMessages_.get(index);
  }
  /**
   * <pre>
   *返回当前版本下的所有员工信息
   * </pre>
   *
   * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
   */
  public com.ljzn.grpc.employee.EmployeeMessageOrBuilder getEmployeeMessagesOrBuilder(
      int index) {
    return employeeMessages_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != 0) {
      output.writeInt32(1, code_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    if (!getServerSecretBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, serverSecret_);
    }
    if (serverVersion_ != 0L) {
      output.writeInt64(4, serverVersion_);
    }
    for (int i = 0; i < employeeMessages_.size(); i++) {
      output.writeMessage(5, employeeMessages_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, code_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    if (!getServerSecretBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, serverSecret_);
    }
    if (serverVersion_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, serverVersion_);
    }
    for (int i = 0; i < employeeMessages_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, employeeMessages_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ljzn.grpc.employee.EmployeeDataApplyResponse)) {
      return super.equals(obj);
    }
    com.ljzn.grpc.employee.EmployeeDataApplyResponse other = (com.ljzn.grpc.employee.EmployeeDataApplyResponse) obj;

    boolean result = true;
    result = result && (getCode()
        == other.getCode());
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && getServerSecret()
        .equals(other.getServerSecret());
    result = result && (getServerVersion()
        == other.getServerVersion());
    result = result && getEmployeeMessagesList()
        .equals(other.getEmployeeMessagesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + SERVER_SECRET_FIELD_NUMBER;
    hash = (53 * hash) + getServerSecret().hashCode();
    hash = (37 * hash) + SERVERVERSION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getServerVersion());
    if (getEmployeeMessagesCount() > 0) {
      hash = (37 * hash) + EMPLOYEEMESSAGES_FIELD_NUMBER;
      hash = (53 * hash) + getEmployeeMessagesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ljzn.grpc.employee.EmployeeDataApplyResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.employee.EmployeeDataApplyResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.employee.EmployeeDataApplyResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.employee.EmployeeDataApplyResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.employee.EmployeeDataApplyResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.employee.EmployeeDataApplyResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.employee.EmployeeDataApplyResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.employee.EmployeeDataApplyResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.employee.EmployeeDataApplyResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.employee.EmployeeDataApplyResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.employee.EmployeeDataApplyResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.employee.EmployeeDataApplyResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ljzn.grpc.employee.EmployeeDataApplyResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code VisitorSystem_cq.EmployeeDataApplyResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:VisitorSystem_cq.EmployeeDataApplyResponse)
      com.ljzn.grpc.employee.EmployeeDataApplyResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljzn.grpc.employee.EmployeeService.internal_static_VisitorSystem_cq_EmployeeDataApplyResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljzn.grpc.employee.EmployeeService.internal_static_VisitorSystem_cq_EmployeeDataApplyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljzn.grpc.employee.EmployeeDataApplyResponse.class, com.ljzn.grpc.employee.EmployeeDataApplyResponse.Builder.class);
    }

    // Construct using com.ljzn.grpc.employee.EmployeeDataApplyResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEmployeeMessagesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      code_ = 0;

      message_ = "";

      serverSecret_ = "";

      serverVersion_ = 0L;

      if (employeeMessagesBuilder_ == null) {
        employeeMessages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        employeeMessagesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ljzn.grpc.employee.EmployeeService.internal_static_VisitorSystem_cq_EmployeeDataApplyResponse_descriptor;
    }

    public com.ljzn.grpc.employee.EmployeeDataApplyResponse getDefaultInstanceForType() {
      return com.ljzn.grpc.employee.EmployeeDataApplyResponse.getDefaultInstance();
    }

    public com.ljzn.grpc.employee.EmployeeDataApplyResponse build() {
      com.ljzn.grpc.employee.EmployeeDataApplyResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ljzn.grpc.employee.EmployeeDataApplyResponse buildPartial() {
      com.ljzn.grpc.employee.EmployeeDataApplyResponse result = new com.ljzn.grpc.employee.EmployeeDataApplyResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.code_ = code_;
      result.message_ = message_;
      result.serverSecret_ = serverSecret_;
      result.serverVersion_ = serverVersion_;
      if (employeeMessagesBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          employeeMessages_ = java.util.Collections.unmodifiableList(employeeMessages_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.employeeMessages_ = employeeMessages_;
      } else {
        result.employeeMessages_ = employeeMessagesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ljzn.grpc.employee.EmployeeDataApplyResponse) {
        return mergeFrom((com.ljzn.grpc.employee.EmployeeDataApplyResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ljzn.grpc.employee.EmployeeDataApplyResponse other) {
      if (other == com.ljzn.grpc.employee.EmployeeDataApplyResponse.getDefaultInstance()) return this;
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (!other.getServerSecret().isEmpty()) {
        serverSecret_ = other.serverSecret_;
        onChanged();
      }
      if (other.getServerVersion() != 0L) {
        setServerVersion(other.getServerVersion());
      }
      if (employeeMessagesBuilder_ == null) {
        if (!other.employeeMessages_.isEmpty()) {
          if (employeeMessages_.isEmpty()) {
            employeeMessages_ = other.employeeMessages_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureEmployeeMessagesIsMutable();
            employeeMessages_.addAll(other.employeeMessages_);
          }
          onChanged();
        }
      } else {
        if (!other.employeeMessages_.isEmpty()) {
          if (employeeMessagesBuilder_.isEmpty()) {
            employeeMessagesBuilder_.dispose();
            employeeMessagesBuilder_ = null;
            employeeMessages_ = other.employeeMessages_;
            bitField0_ = (bitField0_ & ~0x00000010);
            employeeMessagesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEmployeeMessagesFieldBuilder() : null;
          } else {
            employeeMessagesBuilder_.addAllMessages(other.employeeMessages_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ljzn.grpc.employee.EmployeeDataApplyResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ljzn.grpc.employee.EmployeeDataApplyResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int code_ ;
    /**
     * <code>int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }
    /**
     * <code>int32 code = 1;</code>
     */
    public Builder setCode(int value) {
      
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 code = 1;</code>
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object serverSecret_ = "";
    /**
     * <code>string server_secret = 3;</code>
     */
    public java.lang.String getServerSecret() {
      java.lang.Object ref = serverSecret_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverSecret_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string server_secret = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServerSecretBytes() {
      java.lang.Object ref = serverSecret_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverSecret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string server_secret = 3;</code>
     */
    public Builder setServerSecret(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serverSecret_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string server_secret = 3;</code>
     */
    public Builder clearServerSecret() {
      
      serverSecret_ = getDefaultInstance().getServerSecret();
      onChanged();
      return this;
    }
    /**
     * <code>string server_secret = 3;</code>
     */
    public Builder setServerSecretBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serverSecret_ = value;
      onChanged();
      return this;
    }

    private long serverVersion_ ;
    /**
     * <code>int64 serverVersion = 4;</code>
     */
    public long getServerVersion() {
      return serverVersion_;
    }
    /**
     * <code>int64 serverVersion = 4;</code>
     */
    public Builder setServerVersion(long value) {
      
      serverVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 serverVersion = 4;</code>
     */
    public Builder clearServerVersion() {
      
      serverVersion_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.ljzn.grpc.employee.EmployeeMessage> employeeMessages_ =
      java.util.Collections.emptyList();
    private void ensureEmployeeMessagesIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        employeeMessages_ = new java.util.ArrayList<com.ljzn.grpc.employee.EmployeeMessage>(employeeMessages_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ljzn.grpc.employee.EmployeeMessage, com.ljzn.grpc.employee.EmployeeMessage.Builder, com.ljzn.grpc.employee.EmployeeMessageOrBuilder> employeeMessagesBuilder_;

    /**
     * <pre>
     *返回当前版本下的所有员工信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
     */
    public java.util.List<com.ljzn.grpc.employee.EmployeeMessage> getEmployeeMessagesList() {
      if (employeeMessagesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(employeeMessages_);
      } else {
        return employeeMessagesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *返回当前版本下的所有员工信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
     */
    public int getEmployeeMessagesCount() {
      if (employeeMessagesBuilder_ == null) {
        return employeeMessages_.size();
      } else {
        return employeeMessagesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *返回当前版本下的所有员工信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
     */
    public com.ljzn.grpc.employee.EmployeeMessage getEmployeeMessages(int index) {
      if (employeeMessagesBuilder_ == null) {
        return employeeMessages_.get(index);
      } else {
        return employeeMessagesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *返回当前版本下的所有员工信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
     */
    public Builder setEmployeeMessages(
        int index, com.ljzn.grpc.employee.EmployeeMessage value) {
      if (employeeMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeeMessagesIsMutable();
        employeeMessages_.set(index, value);
        onChanged();
      } else {
        employeeMessagesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *返回当前版本下的所有员工信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
     */
    public Builder setEmployeeMessages(
        int index, com.ljzn.grpc.employee.EmployeeMessage.Builder builderForValue) {
      if (employeeMessagesBuilder_ == null) {
        ensureEmployeeMessagesIsMutable();
        employeeMessages_.set(index, builderForValue.build());
        onChanged();
      } else {
        employeeMessagesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *返回当前版本下的所有员工信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
     */
    public Builder addEmployeeMessages(com.ljzn.grpc.employee.EmployeeMessage value) {
      if (employeeMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeeMessagesIsMutable();
        employeeMessages_.add(value);
        onChanged();
      } else {
        employeeMessagesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *返回当前版本下的所有员工信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
     */
    public Builder addEmployeeMessages(
        int index, com.ljzn.grpc.employee.EmployeeMessage value) {
      if (employeeMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeeMessagesIsMutable();
        employeeMessages_.add(index, value);
        onChanged();
      } else {
        employeeMessagesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *返回当前版本下的所有员工信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
     */
    public Builder addEmployeeMessages(
        com.ljzn.grpc.employee.EmployeeMessage.Builder builderForValue) {
      if (employeeMessagesBuilder_ == null) {
        ensureEmployeeMessagesIsMutable();
        employeeMessages_.add(builderForValue.build());
        onChanged();
      } else {
        employeeMessagesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *返回当前版本下的所有员工信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
     */
    public Builder addEmployeeMessages(
        int index, com.ljzn.grpc.employee.EmployeeMessage.Builder builderForValue) {
      if (employeeMessagesBuilder_ == null) {
        ensureEmployeeMessagesIsMutable();
        employeeMessages_.add(index, builderForValue.build());
        onChanged();
      } else {
        employeeMessagesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *返回当前版本下的所有员工信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
     */
    public Builder addAllEmployeeMessages(
        java.lang.Iterable<? extends com.ljzn.grpc.employee.EmployeeMessage> values) {
      if (employeeMessagesBuilder_ == null) {
        ensureEmployeeMessagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, employeeMessages_);
        onChanged();
      } else {
        employeeMessagesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *返回当前版本下的所有员工信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
     */
    public Builder clearEmployeeMessages() {
      if (employeeMessagesBuilder_ == null) {
        employeeMessages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        employeeMessagesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *返回当前版本下的所有员工信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
     */
    public Builder removeEmployeeMessages(int index) {
      if (employeeMessagesBuilder_ == null) {
        ensureEmployeeMessagesIsMutable();
        employeeMessages_.remove(index);
        onChanged();
      } else {
        employeeMessagesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *返回当前版本下的所有员工信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
     */
    public com.ljzn.grpc.employee.EmployeeMessage.Builder getEmployeeMessagesBuilder(
        int index) {
      return getEmployeeMessagesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *返回当前版本下的所有员工信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
     */
    public com.ljzn.grpc.employee.EmployeeMessageOrBuilder getEmployeeMessagesOrBuilder(
        int index) {
      if (employeeMessagesBuilder_ == null) {
        return employeeMessages_.get(index);  } else {
        return employeeMessagesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *返回当前版本下的所有员工信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
     */
    public java.util.List<? extends com.ljzn.grpc.employee.EmployeeMessageOrBuilder> 
         getEmployeeMessagesOrBuilderList() {
      if (employeeMessagesBuilder_ != null) {
        return employeeMessagesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(employeeMessages_);
      }
    }
    /**
     * <pre>
     *返回当前版本下的所有员工信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
     */
    public com.ljzn.grpc.employee.EmployeeMessage.Builder addEmployeeMessagesBuilder() {
      return getEmployeeMessagesFieldBuilder().addBuilder(
          com.ljzn.grpc.employee.EmployeeMessage.getDefaultInstance());
    }
    /**
     * <pre>
     *返回当前版本下的所有员工信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
     */
    public com.ljzn.grpc.employee.EmployeeMessage.Builder addEmployeeMessagesBuilder(
        int index) {
      return getEmployeeMessagesFieldBuilder().addBuilder(
          index, com.ljzn.grpc.employee.EmployeeMessage.getDefaultInstance());
    }
    /**
     * <pre>
     *返回当前版本下的所有员工信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.EmployeeMessage employeeMessages = 5;</code>
     */
    public java.util.List<com.ljzn.grpc.employee.EmployeeMessage.Builder> 
         getEmployeeMessagesBuilderList() {
      return getEmployeeMessagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ljzn.grpc.employee.EmployeeMessage, com.ljzn.grpc.employee.EmployeeMessage.Builder, com.ljzn.grpc.employee.EmployeeMessageOrBuilder> 
        getEmployeeMessagesFieldBuilder() {
      if (employeeMessagesBuilder_ == null) {
        employeeMessagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ljzn.grpc.employee.EmployeeMessage, com.ljzn.grpc.employee.EmployeeMessage.Builder, com.ljzn.grpc.employee.EmployeeMessageOrBuilder>(
                employeeMessages_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        employeeMessages_ = null;
      }
      return employeeMessagesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:VisitorSystem_cq.EmployeeDataApplyResponse)
  }

  // @@protoc_insertion_point(class_scope:VisitorSystem_cq.EmployeeDataApplyResponse)
  private static final com.ljzn.grpc.employee.EmployeeDataApplyResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ljzn.grpc.employee.EmployeeDataApplyResponse();
  }

  public static com.ljzn.grpc.employee.EmployeeDataApplyResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmployeeDataApplyResponse>
      PARSER = new com.google.protobuf.AbstractParser<EmployeeDataApplyResponse>() {
    public EmployeeDataApplyResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EmployeeDataApplyResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EmployeeDataApplyResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmployeeDataApplyResponse> getParserForType() {
    return PARSER;
  }

  public com.ljzn.grpc.employee.EmployeeDataApplyResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

