// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reason/reason.service.proto

package com.ljzn.grpc.reason;

public final class ReasonService {
  private ReasonService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VisitorSystem_cq_ReasonDataApplyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VisitorSystem_cq_ReasonDataApplyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VisitorSystem_cq_ReasonDataApplyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VisitorSystem_cq_ReasonDataApplyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033reason/reason.service.proto\022\020VisitorSy" +
      "stem_cq\032\033reason/reason.message.proto\"e\n\026" +
      "ReasonDataApplyRequest\022\021\n\tclient_id\030\001 \001(" +
      "\t\022\025\n\rclient_secret\030\002 \001(\t\022\017\n\007version\030\003 \001(" +
      "\003\022\020\n\010belongId\030\004 \001(\005\"\237\001\n\027ReasonDataApplyR" +
      "esponse\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\025" +
      "\n\rserver_secret\030\003 \001(\t\022\025\n\rserverVersion\030\004" +
      " \001(\003\0227\n\016reasonMessages\030\005 \003(\0132\037.VisitorSy" +
      "stem_cq.ReasonMessage2}\n\021ReasonAuthServi" +
      "ce\022h\n\017ReasonDataApply\022(.VisitorSystem_cq" +
      ".ReasonDataApplyRequest\032).VisitorSystem_" +
      "cq.ReasonDataApplyResponse\"\000B!\n\024com.ljzn" +
      ".grpc.reasonP\001\242\002\006REASONb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ljzn.grpc.reason.ReasonMessageOuterClass.getDescriptor(),
        }, assigner);
    internal_static_VisitorSystem_cq_ReasonDataApplyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VisitorSystem_cq_ReasonDataApplyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VisitorSystem_cq_ReasonDataApplyRequest_descriptor,
        new java.lang.String[] { "ClientId", "ClientSecret", "Version", "BelongId", });
    internal_static_VisitorSystem_cq_ReasonDataApplyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_VisitorSystem_cq_ReasonDataApplyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VisitorSystem_cq_ReasonDataApplyResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "ServerSecret", "ServerVersion", "ReasonMessages", });
    com.ljzn.grpc.reason.ReasonMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
