// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reason/reason.message.proto

package com.ljzn.grpc.reason;

public final class ReasonMessageOuterClass {
  private ReasonMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VisitorSystem_cq_ReasonMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VisitorSystem_cq_ReasonMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033reason/reason.message.proto\022\020VisitorSy" +
      "stem_cq\"G\n\rReasonMessage\022\020\n\010reasonId\030\001 \001" +
      "(\005\022\022\n\nreasonName\030\002 \001(\t\022\020\n\010belongId\030\003 \001(\005" +
      "B!\n\024com.ljzn.grpc.reasonP\001\242\002\006REASONb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_VisitorSystem_cq_ReasonMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VisitorSystem_cq_ReasonMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VisitorSystem_cq_ReasonMessage_descriptor,
        new java.lang.String[] { "ReasonId", "ReasonName", "BelongId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
