// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: visitor/visitor.message.proto

package com.ljzn.grpc.visitor;

public final class VisitorMessageOuterClass {
  private VisitorMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VisitorSystem_cq_VisitorMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VisitorSystem_cq_VisitorMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VisitorSystem_cq_VisitInfoMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VisitorSystem_cq_VisitInfoMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VisitorSystem_cq_CheckOutMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VisitorSystem_cq_CheckOutMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035visitor/visitor.message.proto\022\020Visitor" +
      "System_cq\"\241\003\n\016VisitorMessage\022\021\n\tvisitorI" +
      "d\030\001 \001(\t\022\016\n\006idType\030\002 \001(\005\022\023\n\013visitorName\030\003" +
      " \001(\t\022\013\n\003sex\030\004 \001(\t\022\016\n\006nation\030\005 \001(\t\022\020\n\010bir" +
      "thday\030\006 \001(\t\022\017\n\007address\030\007 \001(\t\022\016\n\006depart\030\010" +
      " \001(\t\022\025\n\rvalidityBegin\030\t \001(\t\022\023\n\013validityE" +
      "nd\030\n \001(\t\022\017\n\007idPhoto\030\013 \001(\014\022\023\n\013cameraPhoto" +
      "\030\014 \001(\014\022\025\n\rcameraFeature\030\r \001(\014\022\025\n\rfingerF" +
      "eature\030\016 \001(\014\022\016\n\006action\030\017 \001(\005\022\017\n\007version\030" +
      "\020 \001(\003\022\027\n\017faceVerifyScore\030\021 \001(\002\022\030\n\020faceVe" +
      "rifyResult\030\022 \001(\t\022\020\n\010dateTime\030\023 \001(\003\022\017\n\007co" +
      "ntact\030\024 \001(\t\022\020\n\010belongId\030\025 \001(\005\"\267\002\n\020VisitI" +
      "nfoMessage\022\017\n\007visitId\030\001 \001(\t\022\022\n\nemployeeI" +
      "d\030\002 \001(\005\022\021\n\tvisitorId\030\003 \001(\t\022\023\n\013visitorNam" +
      "e\030\004 \001(\t\022\020\n\010reasonId\030\005 \001(\005\022\023\n\013cameraPhoto" +
      "\030\006 \001(\014\022\027\n\017checkInDeviceId\030\007 \001(\t\022\023\n\013check" +
      "InTime\030\010 \001(\003\022\030\n\020checkOutDeviceId\030\t \001(\t\022\024" +
      "\n\014checkOutTime\030\n \001(\003\022\r\n\005state\030\013 \001(\005\022\017\n\007c" +
      "omment\030\014 \001(\t\022\016\n\006action\030\017 \001(\005\022\017\n\007version\030" +
      "\020 \001(\003\022\020\n\010belongId\030\021 \001(\005\"d\n\017CheckOutMessa" +
      "ge\022\017\n\007visitId\030\001 \001(\t\022\030\n\020checkOutDeviceId\030" +
      "\002 \001(\t\022\024\n\014checkOutTime\030\003 \001(\003\022\020\n\010belongId\030" +
      "\004 \001(\005B#\n\025com.ljzn.grpc.visitorP\001\242\002\007VISIT" +
      "ORb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_VisitorSystem_cq_VisitorMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VisitorSystem_cq_VisitorMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VisitorSystem_cq_VisitorMessage_descriptor,
        new java.lang.String[] { "VisitorId", "IdType", "VisitorName", "Sex", "Nation", "Birthday", "Address", "Depart", "ValidityBegin", "ValidityEnd", "IdPhoto", "CameraPhoto", "CameraFeature", "FingerFeature", "Action", "Version", "FaceVerifyScore", "FaceVerifyResult", "DateTime", "Contact", "BelongId", });
    internal_static_VisitorSystem_cq_VisitInfoMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_VisitorSystem_cq_VisitInfoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VisitorSystem_cq_VisitInfoMessage_descriptor,
        new java.lang.String[] { "VisitId", "EmployeeId", "VisitorId", "VisitorName", "ReasonId", "CameraPhoto", "CheckInDeviceId", "CheckInTime", "CheckOutDeviceId", "CheckOutTime", "State", "Comment", "Action", "Version", "BelongId", });
    internal_static_VisitorSystem_cq_CheckOutMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_VisitorSystem_cq_CheckOutMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VisitorSystem_cq_CheckOutMessage_descriptor,
        new java.lang.String[] { "VisitId", "CheckOutDeviceId", "CheckOutTime", "BelongId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
