// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: company/company.service.proto

package com.ljzn.grpc.company;

/**
 * Protobuf type {@code VisitorSystem_cq.CompanyDataApplyResponse}
 */
public  final class CompanyDataApplyResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:VisitorSystem_cq.CompanyDataApplyResponse)
    CompanyDataApplyResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CompanyDataApplyResponse.newBuilder() to construct.
  private CompanyDataApplyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CompanyDataApplyResponse() {
    code_ = 0;
    message_ = "";
    serverSecret_ = "";
    companyMessages_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CompanyDataApplyResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            code_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            serverSecret_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              companyMessages_ = new java.util.ArrayList<com.ljzn.grpc.company.CompanyMessage>();
              mutable_bitField0_ |= 0x00000008;
            }
            companyMessages_.add(
                input.readMessage(com.ljzn.grpc.company.CompanyMessage.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        companyMessages_ = java.util.Collections.unmodifiableList(companyMessages_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ljzn.grpc.company.CompanyService.internal_static_VisitorSystem_cq_CompanyDataApplyResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ljzn.grpc.company.CompanyService.internal_static_VisitorSystem_cq_CompanyDataApplyResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ljzn.grpc.company.CompanyDataApplyResponse.class, com.ljzn.grpc.company.CompanyDataApplyResponse.Builder.class);
  }

  private int bitField0_;
  public static final int CODE_FIELD_NUMBER = 1;
  private int code_;
  /**
   * <code>int32 code = 1;</code>
   */
  public int getCode() {
    return code_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 2;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVER_SECRET_FIELD_NUMBER = 3;
  private volatile java.lang.Object serverSecret_;
  /**
   * <code>string server_secret = 3;</code>
   */
  public java.lang.String getServerSecret() {
    java.lang.Object ref = serverSecret_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serverSecret_ = s;
      return s;
    }
  }
  /**
   * <code>string server_secret = 3;</code>
   */
  public com.google.protobuf.ByteString
      getServerSecretBytes() {
    java.lang.Object ref = serverSecret_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serverSecret_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPANYMESSAGES_FIELD_NUMBER = 4;
  private java.util.List<com.ljzn.grpc.company.CompanyMessage> companyMessages_;
  /**
   * <pre>
   *返回当前版本下的所有部门信息
   * </pre>
   *
   * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
   */
  public java.util.List<com.ljzn.grpc.company.CompanyMessage> getCompanyMessagesList() {
    return companyMessages_;
  }
  /**
   * <pre>
   *返回当前版本下的所有部门信息
   * </pre>
   *
   * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
   */
  public java.util.List<? extends com.ljzn.grpc.company.CompanyMessageOrBuilder> 
      getCompanyMessagesOrBuilderList() {
    return companyMessages_;
  }
  /**
   * <pre>
   *返回当前版本下的所有部门信息
   * </pre>
   *
   * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
   */
  public int getCompanyMessagesCount() {
    return companyMessages_.size();
  }
  /**
   * <pre>
   *返回当前版本下的所有部门信息
   * </pre>
   *
   * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
   */
  public com.ljzn.grpc.company.CompanyMessage getCompanyMessages(int index) {
    return companyMessages_.get(index);
  }
  /**
   * <pre>
   *返回当前版本下的所有部门信息
   * </pre>
   *
   * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
   */
  public com.ljzn.grpc.company.CompanyMessageOrBuilder getCompanyMessagesOrBuilder(
      int index) {
    return companyMessages_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != 0) {
      output.writeInt32(1, code_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    if (!getServerSecretBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, serverSecret_);
    }
    for (int i = 0; i < companyMessages_.size(); i++) {
      output.writeMessage(4, companyMessages_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, code_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    if (!getServerSecretBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, serverSecret_);
    }
    for (int i = 0; i < companyMessages_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, companyMessages_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ljzn.grpc.company.CompanyDataApplyResponse)) {
      return super.equals(obj);
    }
    com.ljzn.grpc.company.CompanyDataApplyResponse other = (com.ljzn.grpc.company.CompanyDataApplyResponse) obj;

    boolean result = true;
    result = result && (getCode()
        == other.getCode());
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && getServerSecret()
        .equals(other.getServerSecret());
    result = result && getCompanyMessagesList()
        .equals(other.getCompanyMessagesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + SERVER_SECRET_FIELD_NUMBER;
    hash = (53 * hash) + getServerSecret().hashCode();
    if (getCompanyMessagesCount() > 0) {
      hash = (37 * hash) + COMPANYMESSAGES_FIELD_NUMBER;
      hash = (53 * hash) + getCompanyMessagesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ljzn.grpc.company.CompanyDataApplyResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.company.CompanyDataApplyResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.company.CompanyDataApplyResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.company.CompanyDataApplyResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.company.CompanyDataApplyResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.company.CompanyDataApplyResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.company.CompanyDataApplyResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.company.CompanyDataApplyResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.company.CompanyDataApplyResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.company.CompanyDataApplyResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.company.CompanyDataApplyResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.company.CompanyDataApplyResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ljzn.grpc.company.CompanyDataApplyResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code VisitorSystem_cq.CompanyDataApplyResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:VisitorSystem_cq.CompanyDataApplyResponse)
      com.ljzn.grpc.company.CompanyDataApplyResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljzn.grpc.company.CompanyService.internal_static_VisitorSystem_cq_CompanyDataApplyResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljzn.grpc.company.CompanyService.internal_static_VisitorSystem_cq_CompanyDataApplyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljzn.grpc.company.CompanyDataApplyResponse.class, com.ljzn.grpc.company.CompanyDataApplyResponse.Builder.class);
    }

    // Construct using com.ljzn.grpc.company.CompanyDataApplyResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCompanyMessagesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      code_ = 0;

      message_ = "";

      serverSecret_ = "";

      if (companyMessagesBuilder_ == null) {
        companyMessages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        companyMessagesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ljzn.grpc.company.CompanyService.internal_static_VisitorSystem_cq_CompanyDataApplyResponse_descriptor;
    }

    public com.ljzn.grpc.company.CompanyDataApplyResponse getDefaultInstanceForType() {
      return com.ljzn.grpc.company.CompanyDataApplyResponse.getDefaultInstance();
    }

    public com.ljzn.grpc.company.CompanyDataApplyResponse build() {
      com.ljzn.grpc.company.CompanyDataApplyResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ljzn.grpc.company.CompanyDataApplyResponse buildPartial() {
      com.ljzn.grpc.company.CompanyDataApplyResponse result = new com.ljzn.grpc.company.CompanyDataApplyResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.code_ = code_;
      result.message_ = message_;
      result.serverSecret_ = serverSecret_;
      if (companyMessagesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          companyMessages_ = java.util.Collections.unmodifiableList(companyMessages_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.companyMessages_ = companyMessages_;
      } else {
        result.companyMessages_ = companyMessagesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ljzn.grpc.company.CompanyDataApplyResponse) {
        return mergeFrom((com.ljzn.grpc.company.CompanyDataApplyResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ljzn.grpc.company.CompanyDataApplyResponse other) {
      if (other == com.ljzn.grpc.company.CompanyDataApplyResponse.getDefaultInstance()) return this;
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (!other.getServerSecret().isEmpty()) {
        serverSecret_ = other.serverSecret_;
        onChanged();
      }
      if (companyMessagesBuilder_ == null) {
        if (!other.companyMessages_.isEmpty()) {
          if (companyMessages_.isEmpty()) {
            companyMessages_ = other.companyMessages_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureCompanyMessagesIsMutable();
            companyMessages_.addAll(other.companyMessages_);
          }
          onChanged();
        }
      } else {
        if (!other.companyMessages_.isEmpty()) {
          if (companyMessagesBuilder_.isEmpty()) {
            companyMessagesBuilder_.dispose();
            companyMessagesBuilder_ = null;
            companyMessages_ = other.companyMessages_;
            bitField0_ = (bitField0_ & ~0x00000008);
            companyMessagesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCompanyMessagesFieldBuilder() : null;
          } else {
            companyMessagesBuilder_.addAllMessages(other.companyMessages_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ljzn.grpc.company.CompanyDataApplyResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ljzn.grpc.company.CompanyDataApplyResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int code_ ;
    /**
     * <code>int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }
    /**
     * <code>int32 code = 1;</code>
     */
    public Builder setCode(int value) {
      
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 code = 1;</code>
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object serverSecret_ = "";
    /**
     * <code>string server_secret = 3;</code>
     */
    public java.lang.String getServerSecret() {
      java.lang.Object ref = serverSecret_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverSecret_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string server_secret = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServerSecretBytes() {
      java.lang.Object ref = serverSecret_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverSecret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string server_secret = 3;</code>
     */
    public Builder setServerSecret(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serverSecret_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string server_secret = 3;</code>
     */
    public Builder clearServerSecret() {
      
      serverSecret_ = getDefaultInstance().getServerSecret();
      onChanged();
      return this;
    }
    /**
     * <code>string server_secret = 3;</code>
     */
    public Builder setServerSecretBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serverSecret_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.ljzn.grpc.company.CompanyMessage> companyMessages_ =
      java.util.Collections.emptyList();
    private void ensureCompanyMessagesIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        companyMessages_ = new java.util.ArrayList<com.ljzn.grpc.company.CompanyMessage>(companyMessages_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ljzn.grpc.company.CompanyMessage, com.ljzn.grpc.company.CompanyMessage.Builder, com.ljzn.grpc.company.CompanyMessageOrBuilder> companyMessagesBuilder_;

    /**
     * <pre>
     *返回当前版本下的所有部门信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
     */
    public java.util.List<com.ljzn.grpc.company.CompanyMessage> getCompanyMessagesList() {
      if (companyMessagesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(companyMessages_);
      } else {
        return companyMessagesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *返回当前版本下的所有部门信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
     */
    public int getCompanyMessagesCount() {
      if (companyMessagesBuilder_ == null) {
        return companyMessages_.size();
      } else {
        return companyMessagesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *返回当前版本下的所有部门信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
     */
    public com.ljzn.grpc.company.CompanyMessage getCompanyMessages(int index) {
      if (companyMessagesBuilder_ == null) {
        return companyMessages_.get(index);
      } else {
        return companyMessagesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *返回当前版本下的所有部门信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
     */
    public Builder setCompanyMessages(
        int index, com.ljzn.grpc.company.CompanyMessage value) {
      if (companyMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCompanyMessagesIsMutable();
        companyMessages_.set(index, value);
        onChanged();
      } else {
        companyMessagesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *返回当前版本下的所有部门信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
     */
    public Builder setCompanyMessages(
        int index, com.ljzn.grpc.company.CompanyMessage.Builder builderForValue) {
      if (companyMessagesBuilder_ == null) {
        ensureCompanyMessagesIsMutable();
        companyMessages_.set(index, builderForValue.build());
        onChanged();
      } else {
        companyMessagesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *返回当前版本下的所有部门信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
     */
    public Builder addCompanyMessages(com.ljzn.grpc.company.CompanyMessage value) {
      if (companyMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCompanyMessagesIsMutable();
        companyMessages_.add(value);
        onChanged();
      } else {
        companyMessagesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *返回当前版本下的所有部门信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
     */
    public Builder addCompanyMessages(
        int index, com.ljzn.grpc.company.CompanyMessage value) {
      if (companyMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCompanyMessagesIsMutable();
        companyMessages_.add(index, value);
        onChanged();
      } else {
        companyMessagesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *返回当前版本下的所有部门信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
     */
    public Builder addCompanyMessages(
        com.ljzn.grpc.company.CompanyMessage.Builder builderForValue) {
      if (companyMessagesBuilder_ == null) {
        ensureCompanyMessagesIsMutable();
        companyMessages_.add(builderForValue.build());
        onChanged();
      } else {
        companyMessagesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *返回当前版本下的所有部门信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
     */
    public Builder addCompanyMessages(
        int index, com.ljzn.grpc.company.CompanyMessage.Builder builderForValue) {
      if (companyMessagesBuilder_ == null) {
        ensureCompanyMessagesIsMutable();
        companyMessages_.add(index, builderForValue.build());
        onChanged();
      } else {
        companyMessagesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *返回当前版本下的所有部门信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
     */
    public Builder addAllCompanyMessages(
        java.lang.Iterable<? extends com.ljzn.grpc.company.CompanyMessage> values) {
      if (companyMessagesBuilder_ == null) {
        ensureCompanyMessagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, companyMessages_);
        onChanged();
      } else {
        companyMessagesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *返回当前版本下的所有部门信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
     */
    public Builder clearCompanyMessages() {
      if (companyMessagesBuilder_ == null) {
        companyMessages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        companyMessagesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *返回当前版本下的所有部门信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
     */
    public Builder removeCompanyMessages(int index) {
      if (companyMessagesBuilder_ == null) {
        ensureCompanyMessagesIsMutable();
        companyMessages_.remove(index);
        onChanged();
      } else {
        companyMessagesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *返回当前版本下的所有部门信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
     */
    public com.ljzn.grpc.company.CompanyMessage.Builder getCompanyMessagesBuilder(
        int index) {
      return getCompanyMessagesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *返回当前版本下的所有部门信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
     */
    public com.ljzn.grpc.company.CompanyMessageOrBuilder getCompanyMessagesOrBuilder(
        int index) {
      if (companyMessagesBuilder_ == null) {
        return companyMessages_.get(index);  } else {
        return companyMessagesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *返回当前版本下的所有部门信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
     */
    public java.util.List<? extends com.ljzn.grpc.company.CompanyMessageOrBuilder> 
         getCompanyMessagesOrBuilderList() {
      if (companyMessagesBuilder_ != null) {
        return companyMessagesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(companyMessages_);
      }
    }
    /**
     * <pre>
     *返回当前版本下的所有部门信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
     */
    public com.ljzn.grpc.company.CompanyMessage.Builder addCompanyMessagesBuilder() {
      return getCompanyMessagesFieldBuilder().addBuilder(
          com.ljzn.grpc.company.CompanyMessage.getDefaultInstance());
    }
    /**
     * <pre>
     *返回当前版本下的所有部门信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
     */
    public com.ljzn.grpc.company.CompanyMessage.Builder addCompanyMessagesBuilder(
        int index) {
      return getCompanyMessagesFieldBuilder().addBuilder(
          index, com.ljzn.grpc.company.CompanyMessage.getDefaultInstance());
    }
    /**
     * <pre>
     *返回当前版本下的所有部门信息
     * </pre>
     *
     * <code>repeated .VisitorSystem_cq.CompanyMessage companyMessages = 4;</code>
     */
    public java.util.List<com.ljzn.grpc.company.CompanyMessage.Builder> 
         getCompanyMessagesBuilderList() {
      return getCompanyMessagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ljzn.grpc.company.CompanyMessage, com.ljzn.grpc.company.CompanyMessage.Builder, com.ljzn.grpc.company.CompanyMessageOrBuilder> 
        getCompanyMessagesFieldBuilder() {
      if (companyMessagesBuilder_ == null) {
        companyMessagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ljzn.grpc.company.CompanyMessage, com.ljzn.grpc.company.CompanyMessage.Builder, com.ljzn.grpc.company.CompanyMessageOrBuilder>(
                companyMessages_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        companyMessages_ = null;
      }
      return companyMessagesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:VisitorSystem_cq.CompanyDataApplyResponse)
  }

  // @@protoc_insertion_point(class_scope:VisitorSystem_cq.CompanyDataApplyResponse)
  private static final com.ljzn.grpc.company.CompanyDataApplyResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ljzn.grpc.company.CompanyDataApplyResponse();
  }

  public static com.ljzn.grpc.company.CompanyDataApplyResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CompanyDataApplyResponse>
      PARSER = new com.google.protobuf.AbstractParser<CompanyDataApplyResponse>() {
    public CompanyDataApplyResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CompanyDataApplyResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CompanyDataApplyResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CompanyDataApplyResponse> getParserForType() {
    return PARSER;
  }

  public com.ljzn.grpc.company.CompanyDataApplyResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

