// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: company/company.message.proto

package com.ljzn.grpc.company;

public interface CompanyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VisitorSystem_cq.CompanyMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *uuid
   * </pre>
   *
   * <code>int32 belongId = 1;</code>
   */
  int getBelongId();

  /**
   * <code>string description = 2;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>int32 parentId = 3;</code>
   */
  int getParentId();
}
